import type {
  GeneratorDef,
  MilestoneDef,
  UpgradeDef,
  WorkerDef,
} from '../types'

export const GENERATORS: GeneratorDef[] = [
  {
    id: 'sapling',
    name: 'Sapling',
    blurb: 'Young trees drip warm resin on their own.',
    baseCost: 15,
    costGrowth: 1.14,
    baseRate: 0.1,
  },
  {
    id: 'dripvine',
    name: 'Dripvine',
    blurb: 'Climbing vines wick sap into little cups.',
    baseCost: 100,
    costGrowth: 1.14,
    baseRate: 0.5,
  },
  {
    id: 'firefly',
    name: 'Firefly Swarm',
    blurb: 'Tiny lights herd stray sparks into jars.',
    baseCost: 500,
    costGrowth: 1.14,
    baseRate: 2.2,
  },
  {
    id: 'resinpress',
    name: 'Resin Press',
    blurb: 'Wooden plates squeeze every last drop.',
    baseCost: 2200,
    costGrowth: 1.14,
    baseRate: 10,
  },
  {
    id: 'kiln',
    name: 'Resin Kiln',
    blurb: 'Slow heat concentrates droplets into wealth.',
    baseCost: 9000,
    costGrowth: 1.13,
    baseRate: 36,
  },
  {
    id: 'ambermill',
    name: 'Amber Mill',
    blurb: 'Stone wheels grind hardened sap to gold-dust.',
    baseCost: 42000,
    costGrowth: 1.13,
    baseRate: 120,
  },
  {
    id: 'groveheart',
    name: 'Groveheart',
    blurb: 'A living core that sings resin into being.',
    baseCost: 180000,
    costGrowth: 1.13,
    baseRate: 420,
  },
  {
    id: 'starroot',
    name: 'Starroot',
    blurb: 'Deep roots drink starlight and weep amber.',
    baseCost: 950000,
    costGrowth: 1.12,
    baseRate: 1600,
  },
]

export const WORKERS: WorkerDef[] = [
  {
    id: 'sproutling',
    name: 'Sproutling',
    blurb: 'A leaf-hatted kid who toddles resin pots home.',
    baseCost: 25,
    costGrowth: 1.16,
    baseRate: 0.2,
    speed: 42,
    hue: '#7ecf7a',
    accent: '#3d6b3a',
    size: 0.85,
    maxVisible: 8,
  },
  {
    id: 'amberkin',
    name: 'Amberkin',
    blurb: 'Glowing gatherers with sticky fingers.',
    baseCost: 180,
    costGrowth: 1.15,
    baseRate: 1.4,
    speed: 55,
    hue: '#f0b45a',
    accent: '#a86a28',
    size: 0.95,
    maxVisible: 7,
  },
  {
    id: 'barkwalker',
    name: 'Barkwalker',
    blurb: 'Backpackers who strip drip-lines from trunks.',
    baseCost: 1200,
    costGrowth: 1.15,
    baseRate: 8,
    speed: 48,
    hue: '#c4a484',
    accent: '#5c4030',
    size: 1.05,
    maxVisible: 6,
  },
  {
    id: 'lanternfolk',
    name: 'Lanternfolk',
    blurb: 'Night guides who find sap in the shade.',
    baseCost: 7500,
    costGrowth: 1.14,
    baseRate: 40,
    speed: 62,
    hue: '#8ec8d4',
    accent: '#f6d56a',
    size: 1,
    maxVisible: 5,
  },
  {
    id: 'cartbearer',
    name: 'Cartbearer',
    blurb: 'Little wagons haul heavy resin barrels.',
    baseCost: 45000,
    costGrowth: 1.14,
    baseRate: 180,
    speed: 38,
    hue: '#d4896a',
    accent: '#6b3a2a',
    size: 1.2,
    maxVisible: 4,
  },
  {
    id: 'grovewarden',
    name: 'Grovewarden',
    blurb: 'Keepers who coax the whole grove to give.',
    baseCost: 260000,
    costGrowth: 1.13,
    baseRate: 850,
    speed: 50,
    hue: '#9ad1a0',
    accent: '#f0b45a',
    size: 1.15,
    maxVisible: 3,
  },
]

export const UPGRADES: UpgradeDef[] = [
  {
    id: 'tapStrength',
    name: 'Keen Tap',
    blurb: 'Each touch pulls more resin from the bark.',
    baseCost: 50,
    costGrowth: 1.55,
    effectLabel: '+1 tap',
  },
  {
    id: 'stickyFingers',
    name: 'Sticky Fingers',
    blurb: 'Tap power grows with every Keen Tap you own.',
    baseCost: 400,
    costGrowth: 1.7,
    effectLabel: '+12% tap',
  },
  {
    id: 'keenCrit',
    name: 'Lucky Strike',
    blurb: 'Chance for taps to shower extra resin.',
    baseCost: 900,
    costGrowth: 1.75,
    effectLabel: '+4% crit',
  },
  {
    id: 'resinVein',
    name: 'Resin Vein',
    blurb: 'Buildings run a little richer.',
    baseCost: 250,
    costGrowth: 1.65,
    effectLabel: '+15% buildings',
  },
  {
    id: 'emberChorus',
    name: 'Ember Chorus',
    blurb: 'The grove hums; buildings surge.',
    baseCost: 3500,
    costGrowth: 1.7,
    effectLabel: '+20% buildings',
  },
  {
    id: 'sapSymphony',
    name: 'Sap Symphony',
    blurb: 'Workers and buildings share one melody.',
    baseCost: 18000,
    costGrowth: 1.75,
    effectLabel: '+18% all',
  },
  {
    id: 'swiftFeet',
    name: 'Swift Feet',
    blurb: 'Workers scamper faster between trees.',
    baseCost: 600,
    costGrowth: 1.6,
    effectLabel: '+12% workers',
  },
  {
    id: 'heavyPails',
    name: 'Heavy Pails',
    blurb: 'Bigger buckets mean fatter trips.',
    baseCost: 2800,
    costGrowth: 1.65,
    effectLabel: '+20% workers',
  },
  {
    id: 'nightLanterns',
    name: 'Night Lanterns',
    blurb: 'Fireflies and lanternfolk shine brighter.',
    baseCost: 5000,
    costGrowth: 1.8,
    effectLabel: '+35% light folk',
  },
  {
    id: 'kilnDraft',
    name: 'Kiln Draft',
    blurb: 'Hotter air for presses, kilns, and mills.',
    baseCost: 12000,
    costGrowth: 1.8,
    effectLabel: '+30% heat works',
  },
  {
    id: 'goldenSap',
    name: 'Golden Sap',
    blurb: 'Everything the grove makes turns richer.',
    baseCost: 75000,
    costGrowth: 2,
    effectLabel: '+25% global',
  },
  {
    id: 'deepRoots',
    name: 'Deep Roots',
    blurb: 'Offline growth holds longer in the soil.',
    baseCost: 8000,
    costGrowth: 1.9,
    effectLabel: '+50% offline cap',
  },
]

export const MILESTONES: MilestoneDef[] = [
  {
    id: 'firstDrip',
    name: 'First Drip',
    blurb: 'Gather 50 total resin.',
    needTotal: 50,
    reward: 40,
  },
  {
    id: 'hiredHelp',
    name: 'Hired Help',
    blurb: 'Reach 500 total resin.',
    needTotal: 500,
    reward: 350,
  },
  {
    id: 'warmKiln',
    name: 'Warm Kiln',
    blurb: 'Reach 5,000 total resin.',
    needTotal: 5000,
    reward: 4000,
  },
  {
    id: 'busyGrove',
    name: 'Busy Grove',
    blurb: 'Reach 50,000 total resin.',
    needTotal: 50000,
    reward: 45000,
  },
  {
    id: 'amberRush',
    name: 'Amber Rush',
    blurb: 'Reach 250,000 total resin.',
    needTotal: 250000,
    reward: 200000,
  },
  {
    id: 'canopySong',
    name: 'Canopy Song',
    blurb: 'Reach 1,000,000 total resin.',
    needTotal: 1_000_000,
    reward: 900000,
  },
  {
    id: 'starlit',
    name: 'Starlit Canopy',
    blurb: 'Reach 10,000,000 total resin.',
    needTotal: 10_000_000,
    reward: 8_000_000,
  },
]

export const SAVE_KEY = 'kindlewood-save-v2'
export const MAX_OFFLINE_MS = 1000 * 60 * 60 * 8
export const MAX_VISIBLE_WORKERS = 22
