import type {
  GeneratorDef,
  MilestoneDef,
  PrestigeDef,
  UpgradeDef,
  WorkerDef,
  ZoneDef,
} from '../types'

export const ZONES: ZoneDef[] = [
  {
    id: 'clearing',
    name: 'Sun Clearing',
    blurb: 'Your first grove. Always open.',
    resinCost: 0,
    sparkCost: 0,
    skyTop: '#1a3a48',
    skyBot: '#6d8f4e',
    ground: '#3f5d34',
    groundDark: '#2f4a2a',
  },
  {
    id: 'brook',
    name: 'Amber Brook',
    blurb: 'A resin-fed stream. Wider forage paths.',
    resinCost: 2500,
    sparkCost: 0,
    skyTop: '#1a4050',
    skyBot: '#5a8f7a',
    ground: '#3a6a58',
    groundDark: '#2a5044',
  },
  {
    id: 'hollow',
    name: 'Moss Hollow',
    blurb: 'Damp shade and fat drip-lines.',
    resinCost: 35000,
    sparkCost: 0,
    skyTop: '#163238',
    skyBot: '#4a6e52',
    ground: '#355540',
    groundDark: '#24382c',
  },
  {
    id: 'ridge',
    name: 'Kiln Ridge',
    blurb: 'Windy heights for mills and forges.',
    resinCost: 400000,
    sparkCost: 1,
    skyTop: '#2a3048',
    skyBot: '#7a6a48',
    ground: '#5a5340',
    groundDark: '#3a362c',
  },
  {
    id: 'canopy',
    name: 'High Canopy',
    blurb: 'Leaf-roads above the world.',
    resinCost: 5_000_000,
    sparkCost: 3,
    skyTop: '#204858',
    skyBot: '#6aa070',
    ground: '#457a52',
    groundDark: '#2e5238',
  },
  {
    id: 'starfall',
    name: 'Starfall Glade',
    blurb: 'Where night-sap becomes starlight.',
    resinCost: 80_000_000,
    sparkCost: 8,
    skyTop: '#12182e',
    skyBot: '#3a4a78',
    ground: '#2a3558',
    groundDark: '#1a2238',
  },
]

export const GENERATORS: GeneratorDef[] = [
  {
    id: 'sapling',
    name: 'Sapling',
    blurb: 'Young trees drip warm resin on their own.',
    baseCost: 15,
    costGrowth: 1.14,
    baseRate: 0.1,
    zone: 'clearing',
  },
  {
    id: 'dripvine',
    name: 'Dripvine',
    blurb: 'Climbing vines wick sap into little cups.',
    baseCost: 100,
    costGrowth: 1.14,
    baseRate: 0.5,
    zone: 'clearing',
  },
  {
    id: 'firefly',
    name: 'Firefly Swarm',
    blurb: 'Tiny lights herd stray sparks into jars.',
    baseCost: 500,
    costGrowth: 1.14,
    baseRate: 2.2,
    zone: 'brook',
  },
  {
    id: 'resinpress',
    name: 'Resin Press',
    blurb: 'Wooden plates squeeze every last drop.',
    baseCost: 2200,
    costGrowth: 1.14,
    baseRate: 10,
    zone: 'brook',
  },
  {
    id: 'kiln',
    name: 'Resin Kiln',
    blurb: 'Slow heat concentrates droplets into wealth.',
    baseCost: 9000,
    costGrowth: 1.13,
    baseRate: 36,
    zone: 'hollow',
  },
  {
    id: 'ambermill',
    name: 'Amber Mill',
    blurb: 'Stone wheels grind hardened sap to gold-dust.',
    baseCost: 42000,
    costGrowth: 1.13,
    baseRate: 120,
    zone: 'hollow',
  },
  {
    id: 'honeycomb',
    name: 'Honeycomb Nest',
    blurb: 'Wild bees seal resin into sweet cells.',
    baseCost: 180000,
    costGrowth: 1.13,
    baseRate: 380,
    zone: 'ridge',
  },
  {
    id: 'groveheart',
    name: 'Groveheart',
    blurb: 'A living core that sings resin into being.',
    baseCost: 750000,
    costGrowth: 1.12,
    baseRate: 1100,
    zone: 'ridge',
  },
  {
    id: 'sapforge',
    name: 'Sapforge',
    blurb: 'Molten amber hammered into pure income.',
    baseCost: 4_000_000,
    costGrowth: 1.12,
    baseRate: 4200,
    zone: 'canopy',
  },
  {
    id: 'starroot',
    name: 'Starroot',
    blurb: 'Deep roots drink starlight and weep amber.',
    baseCost: 22_000_000,
    costGrowth: 1.12,
    baseRate: 16000,
    zone: 'canopy',
  },
  {
    id: 'moonwell',
    name: 'Moonwell',
    blurb: 'A silver pool that fills while you sleep.',
    baseCost: 140_000_000,
    costGrowth: 1.11,
    baseRate: 72000,
    zone: 'starfall',
  },
  {
    id: 'worldtree',
    name: 'Worldtree',
    blurb: 'The grove’s crown. Income that remakes maps.',
    baseCost: 950_000_000,
    costGrowth: 1.11,
    baseRate: 380000,
    zone: 'starfall',
  },
]

export const WORKERS: WorkerDef[] = [
  {
    id: 'sproutling',
    name: 'Sproutling',
    blurb: 'A leaf-hatted kid who toddles resin pots home.',
    baseCost: 25,
    costGrowth: 1.16,
    baseRate: 0.2,
    speed: 42,
    hue: '#7ecf7a',
    accent: '#3d6b3a',
    size: 0.85,
    maxVisible: 7,
    zone: 'clearing',
  },
  {
    id: 'amberkin',
    name: 'Amberkin',
    blurb: 'Glowing gatherers with sticky fingers.',
    baseCost: 180,
    costGrowth: 1.15,
    baseRate: 1.4,
    speed: 55,
    hue: '#f0b45a',
    accent: '#a86a28',
    size: 0.95,
    maxVisible: 6,
    zone: 'clearing',
  },
  {
    id: 'barkwalker',
    name: 'Barkwalker',
    blurb: 'Backpackers who strip drip-lines from trunks.',
    baseCost: 1200,
    costGrowth: 1.15,
    baseRate: 8,
    speed: 48,
    hue: '#c4a484',
    accent: '#5c4030',
    size: 1.05,
    maxVisible: 5,
    zone: 'brook',
  },
  {
    id: 'mossrunner',
    name: 'Mossrunner',
    blurb: 'Soft-footed sprinters of the damp hollow.',
    baseCost: 4500,
    costGrowth: 1.14,
    baseRate: 22,
    speed: 70,
    hue: '#6ab08a',
    accent: '#2f5a44',
    size: 0.9,
    maxVisible: 5,
    zone: 'hollow',
  },
  {
    id: 'lanternfolk',
    name: 'Lanternfolk',
    blurb: 'Night guides who find sap in the shade.',
    baseCost: 15000,
    costGrowth: 1.14,
    baseRate: 55,
    speed: 62,
    hue: '#8ec8d4',
    accent: '#f6d56a',
    size: 1,
    maxVisible: 4,
    zone: 'hollow',
  },
  {
    id: 'cartbearer',
    name: 'Cartbearer',
    blurb: 'Little wagons haul heavy resin barrels.',
    baseCost: 65000,
    costGrowth: 1.14,
    baseRate: 200,
    speed: 38,
    hue: '#d4896a',
    accent: '#6b3a2a',
    size: 1.2,
    maxVisible: 4,
    zone: 'ridge',
  },
  {
    id: 'driplingscout',
    name: 'Dripling Scout',
    blurb: 'Pathfinders who open new drip routes.',
    baseCost: 280000,
    costGrowth: 1.13,
    baseRate: 700,
    speed: 66,
    hue: '#b8d46a',
    accent: '#5a7030',
    size: 1,
    maxVisible: 3,
    zone: 'ridge',
  },
  {
    id: 'grovewarden',
    name: 'Grovewarden',
    blurb: 'Keepers who coax the whole grove to give.',
    baseCost: 1_200_000,
    costGrowth: 1.13,
    baseRate: 2400,
    speed: 50,
    hue: '#9ad1a0',
    accent: '#f0b45a',
    size: 1.15,
    maxVisible: 3,
    zone: 'canopy',
  },
  {
    id: 'emberbearer',
    name: 'Emberbearer',
    blurb: 'Carry living coals that ripen sap mid-walk.',
    baseCost: 8_000_000,
    costGrowth: 1.12,
    baseRate: 12000,
    speed: 44,
    hue: '#e89050',
    accent: '#8a3020',
    size: 1.1,
    maxVisible: 3,
    zone: 'canopy',
  },
  {
    id: 'astralmote',
    name: 'Astral Mote',
    blurb: 'Star-motes that sip resin from the night air.',
    baseCost: 55_000_000,
    costGrowth: 1.12,
    baseRate: 65000,
    speed: 80,
    hue: '#c8b8ff',
    accent: '#f0e8a0',
    size: 0.8,
    maxVisible: 4,
    zone: 'starfall',
  },
]

export const UPGRADES: UpgradeDef[] = [
  {
    id: 'tapStrength',
    name: 'Keen Tap',
    blurb: 'Each touch pulls more resin from the bark.',
    baseCost: 50,
    costGrowth: 1.55,
    effectLabel: '+1 tap',
  },
  {
    id: 'stickyFingers',
    name: 'Sticky Fingers',
    blurb: 'Tap power scales harder.',
    baseCost: 400,
    costGrowth: 1.7,
    effectLabel: '+12% tap',
  },
  {
    id: 'keenCrit',
    name: 'Lucky Strike',
    blurb: 'Chance for taps to shower extra resin.',
    baseCost: 900,
    costGrowth: 1.75,
    effectLabel: '+4% crit',
  },
  {
    id: 'doubleDip',
    name: 'Double Dip',
    blurb: 'Crits hit even harder.',
    baseCost: 12000,
    costGrowth: 1.85,
    effectLabel: '+1 crit mult',
  },
  {
    id: 'resinVein',
    name: 'Resin Vein',
    blurb: 'Buildings run a little richer.',
    baseCost: 250,
    costGrowth: 1.65,
    effectLabel: '+15% buildings',
  },
  {
    id: 'emberChorus',
    name: 'Ember Chorus',
    blurb: 'The grove hums; buildings surge.',
    baseCost: 3500,
    costGrowth: 1.7,
    effectLabel: '+20% buildings',
  },
  {
    id: 'sapSymphony',
    name: 'Sap Symphony',
    blurb: 'Workers and buildings share one melody.',
    baseCost: 18000,
    costGrowth: 1.75,
    effectLabel: '+18% all',
  },
  {
    id: 'canopyYield',
    name: 'Canopy Yield',
    blurb: 'Higher zones drip thicker.',
    baseCost: 90000,
    costGrowth: 1.8,
    effectLabel: '+10%/zone',
  },
  {
    id: 'swiftFeet',
    name: 'Swift Feet',
    blurb: 'Workers scamper faster between trees.',
    baseCost: 600,
    costGrowth: 1.6,
    effectLabel: '+12% workers',
  },
  {
    id: 'heavyPails',
    name: 'Heavy Pails',
    blurb: 'Bigger buckets mean fatter trips.',
    baseCost: 2800,
    costGrowth: 1.65,
    effectLabel: '+20% workers',
  },
  {
    id: 'packTrain',
    name: 'Pack Train',
    blurb: 'Carts and scouts haul like a convoy.',
    baseCost: 45000,
    costGrowth: 1.75,
    effectLabel: '+25% haul folk',
  },
  {
    id: 'nightLanterns',
    name: 'Night Lanterns',
    blurb: 'Fireflies and lanternfolk shine brighter.',
    baseCost: 5000,
    costGrowth: 1.8,
    effectLabel: '+35% light folk',
  },
  {
    id: 'kilnDraft',
    name: 'Kiln Draft',
    blurb: 'Hotter air for presses, kilns, and mills.',
    baseCost: 12000,
    costGrowth: 1.8,
    effectLabel: '+30% heat works',
  },
  {
    id: 'forgeBellows',
    name: 'Forge Bellows',
    blurb: 'Sapforges and worldtrees roar.',
    baseCost: 250000,
    costGrowth: 1.85,
    effectLabel: '+40% late forges',
  },
  {
    id: 'goldenSap',
    name: 'Golden Sap',
    blurb: 'Everything the grove makes turns richer.',
    baseCost: 75000,
    costGrowth: 2,
    effectLabel: '+25% global',
  },
  {
    id: 'deepRoots',
    name: 'Deep Roots',
    blurb: 'Offline growth holds longer in the soil.',
    baseCost: 8000,
    costGrowth: 1.9,
    effectLabel: '+50% offline cap',
  },
  {
    id: 'timekeeper',
    name: 'Timekeeper',
    blurb: 'Passive ticks feel denser.',
    baseCost: 200000,
    costGrowth: 1.9,
    effectLabel: '+8% income',
  },
]

export const PRESTIGE: PrestigeDef[] = [
  {
    id: 'eternalTap',
    name: 'Eternal Tap',
    blurb: 'Keep a stronger tap after every rebirth.',
    baseCost: 1,
    costGrowth: 1.8,
    effectLabel: '+2 base tap',
    maxLevel: 25,
  },
  {
    id: 'sparkMulch',
    name: 'Spark Mulch',
    blurb: 'Each Amber Spark feeds the whole grove.',
    baseCost: 1,
    costGrowth: 2,
    effectLabel: '+3%/spark',
    maxLevel: 20,
  },
  {
    id: 'starterCrew',
    name: 'Starter Crew',
    blurb: 'Begin each run with free Sproutlings.',
    baseCost: 2,
    costGrowth: 2.2,
    effectLabel: '+1 sproutling',
    maxLevel: 10,
  },
  {
    id: 'deepMemory',
    name: 'Deep Memory',
    blurb: 'Offline gains stretch further forever.',
    baseCost: 2,
    costGrowth: 2,
    effectLabel: '+40% offline',
    maxLevel: 15,
  },
  {
    id: 'zoneEcho',
    name: 'Zone Echo',
    blurb: 'Unlocked areas produce louder.',
    baseCost: 3,
    costGrowth: 2.1,
    effectLabel: '+12%/zone',
    maxLevel: 12,
  },
  {
    id: 'criticalFate',
    name: 'Critical Fate',
    blurb: 'Permanent luck on every tap.',
    baseCost: 4,
    costGrowth: 2.3,
    effectLabel: '+3% crit',
    maxLevel: 10,
  },
  {
    id: 'worldPulse',
    name: 'World Pulse',
    blurb: 'A flat multiplier that survives rebirth.',
    baseCost: 5,
    costGrowth: 2.5,
    effectLabel: '+20% global',
    maxLevel: 15,
  },
]

export const MILESTONES: MilestoneDef[] = [
  {
    id: 'firstDrip',
    name: 'First Drip',
    blurb: 'Gather 50 resin this run.',
    needTotal: 50,
    reward: 40,
  },
  {
    id: 'hiredHelp',
    name: 'Hired Help',
    blurb: 'Reach 500 resin this run.',
    needTotal: 500,
    reward: 350,
  },
  {
    id: 'warmKiln',
    name: 'Warm Kiln',
    blurb: 'Reach 5,000 resin this run.',
    needTotal: 5000,
    reward: 4000,
  },
  {
    id: 'busyGrove',
    name: 'Busy Grove',
    blurb: 'Reach 50,000 resin this run.',
    needTotal: 50000,
    reward: 45000,
  },
  {
    id: 'amberRush',
    name: 'Amber Rush',
    blurb: 'Reach 250,000 resin this run.',
    needTotal: 250000,
    reward: 200000,
  },
  {
    id: 'canopySong',
    name: 'Canopy Song',
    blurb: 'Reach 1,000,000 resin this run.',
    needTotal: 1_000_000,
    reward: 900000,
  },
  {
    id: 'starlit',
    name: 'Starlit Canopy',
    blurb: 'Reach 10,000,000 resin this run.',
    needTotal: 10_000_000,
    reward: 8_000_000,
  },
  {
    id: 'worldAwake',
    name: 'World Awake',
    blurb: 'Reach 100,000,000 resin this run.',
    needTotal: 100_000_000,
    reward: 75_000_000,
  },
  {
    id: 'firstRebirth',
    name: 'First Rebirth',
    blurb: 'Rebirth the grove at least once.',
    needTotal: 0,
    needRebirths: 1,
    reward: 5000,
  },
  {
    id: 'sparkCollector',
    name: 'Spark Collector',
    blurb: 'Hold 10 Amber Sparks at once.',
    needTotal: 0,
    needSparks: 10,
    reward: 250000,
  },
]

export const SAVE_KEY = 'kindlewood-save-v3'
export const MAX_OFFLINE_MS = 1000 * 60 * 60 * 8
export const MAX_VISIBLE_WORKERS = 28
export const REBIRTH_DIVISOR = 1_000_000
