"""Generate C# from the design sheets."""
import argparse
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import preflight  # noqa: E402

CORE_OUT = os.path.join(ROOT, "src", "InkwellWorld.Core", "Generated")

NAMES = {
    "characters": ("CharacterDef", "Characters"),
    "abilities": ("AbilityDef", "Abilities"),
    "systems": ("SystemDef", "Systems"),
    "hooks": ("HookDef", "Hooks"),
}


def pascal(s):
    return "".join(p[:1].upper() + p[1:] for p in s.replace(".", "_").split("_") if p)


def cs_type(spec):
    t = spec["type"]
    return {
        "string": "string",
        "enum": "string",
        "ref": "string",
        "number": "float",
        "int": "int",
        "bool": "bool",
        "ref[]": "string[]",
        "string[]": "string[]",
    }[t]


def lit_str(v):
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'


def literal(spec, v):
    t = cs_type(spec)
    if v is None or v == "":
        return None
    if t == "string":
        return lit_str(v)
    if t == "float":
        return repr(float(v)) + "f"
    if t == "int":
        return str(int(v))
    if t == "bool":
        return "true" if v else "false"
    if t == "string[]":
        return "new[] { " + ", ".join(lit_str(x) for x in v) + " }" if v else "new string[0]"
    raise ValueError(t)


def gen_sheet(sheet, s, draft):
    cls, table = NAMES[sheet]
    lines = [
        "// <auto-generated>",
        "// From design/sheets/%s.json by tools/gen_cs.py." % sheet,
        "// </auto-generated>",
        "using System.Linq;",
        "",
        "namespace InkwellWorld.Generated",
        "{",
        "    public sealed partial class %s" % cls,
        "    {",
    ]
    for col, spec in s["columns"].items():
        lines.append("        public %s %s;" % (cs_type(spec), pascal(col)))
    lines += [
        "    }",
        "",
        "    public static partial class %s" % table,
        "    {",
        "        public static readonly %s[] All =" % cls,
        "        {",
    ]
    for r in s["rows"]:
        parts = []
        for col, spec in s["columns"].items():
            lit = literal(spec, r.get(col))
            if lit is not None:
                parts.append("%s = %s" % (pascal(col), lit))
        lines.append("            new %s { %s }," % (cls, ", ".join(parts)))
    lines += [
        "        };",
        "",
        "        public static %s Get(string id) => All.First(x => x.Id == id);" % cls,
        "    }",
        "}",
        "",
    ]
    os.makedirs(CORE_OUT, exist_ok=True)
    path = os.path.join(CORE_OUT, pascal(sheet) + ".g.cs")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote", path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gate", default=None)
    ap.add_argument("--draft", action="store_true")
    args = ap.parse_args()
    if args.gate and not args.draft:
        rc = subprocess.call([sys.executable, os.path.join(ROOT, "tools", "preflight.py"), "--gate", args.gate, "-q"])
        if rc != 0:
            print("preflight failed; fix sheets or pass --draft", file=sys.stderr)
            sys.exit(rc)
    sheets = preflight.load_sheets()
    for name, s in sheets.items():
        if name in NAMES:
            gen_sheet(name, s, args.draft)


if __name__ == "__main__":
    main()
